/**
 * @helix-treasury/sdk
 *
 * TypeScript client for interacting with a deployed Helix treasury system.
 * Wraps viem calls to ProposalRegistry, TreasuryVault, PolicyRegistry, and TaxEngine.
 *
 * Usage:
 *   const client = new HelixClient({ vaultAddress: "0x...", rpcUrl: "https://..." });
 *   const nav = await client.getNAV();
 *   const proposals = await client.listProposals({ state: "pending" });
 */

import { createPublicClient, createWalletClient, http, type Address, type PublicClient, type WalletClient, type Chain } from "viem";
import { arbitrumSepolia } from "viem/chains";

// ─── ABI fragments (auto-generated by `forge inspect` in CI; hand-written stubs here) ───

const TREASURY_VAULT_ABI = [
  { type: "function", name: "getNAV", inputs: [], outputs: [{ type: "uint256", name: "totalNAVUsdc" }], stateMutability: "view" },
  { type: "function", name: "getState", inputs: [], outputs: [{ type: "tuple[]", name: "entries", components: [{ type: "address", name: "token" }, { type: "uint8", name: "decimals" }, { type: "bool", name: "isStable" }, { type: "bool", name: "isLiquid" }, { type: "uint8", name: "protocol" }, { type: "address", name: "adapter" }, { type: "bool", name: "active" }] }, { type: "uint256[]", name: "balances" }], stateMutability: "view" },
  { type: "function", name: "paused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "safe", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "guardian", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "deposit", inputs: [{ type: "address", name: "token" }, { type: "uint256", name: "amount" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ type: "address", name: "token" }, { type: "uint256", name: "amount" }, { type: "address", name: "to" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "executeApproved", inputs: [{ type: "bytes32", name: "proposalId" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "emergencyPause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "emergencyUnpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "registerAsset", inputs: [{ type: "tuple", name: "entry", components: [{ type: "address", name: "token" }, { type: "uint8", name: "decimals" }, { type: "bool", name: "isStable" }, { type: "bool", name: "isLiquid" }, { type: "uint8", name: "protocol" }, { type: "address", name: "adapter" }, { type: "bool", name: "active" }] }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "deregisterAsset", inputs: [{ type: "address", name: "token" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "Deposited", inputs: [{ type: "address", name: "from", indexed: true }, { type: "address", name: "token", indexed: true }, { type: "uint256", name: "amount" }] },
  { type: "event", name: "Executed", inputs: [{ type: "bytes32", name: "proposalId", indexed: true }] },
  { type: "event", name: "AssetRegistered", inputs: [{ type: "address", name: "token", indexed: true }, { type: "bytes32", name: "adapter" }] },
  { type: "event", name: "AssetDeregistered", inputs: [{ type: "address", name: "token", indexed: true }] },
  { type: "event", name: "EmergencyPaused", inputs: [{ type: "address", name: "by" }] },
  { type: "event", name: "EmergencyUnpaused", inputs: [{ type: "address", name: "by" }] },
  { type: "event", name: "ActionDispatched", inputs: [{ type: "uint8", name: "actionType", indexed: true }, { type: "address", name: "adapter", indexed: true }, { type: "bytes", name: "data" }] },
] as const;

const PROPOSAL_REGISTRY_ABI = [
  { type: "function", name: "getProposal", inputs: [{ type: "bytes32", name: "id" }], outputs: [{ type: "tuple", name: "proposal", components: [{ type: "bytes32", name: "id" }, { type: "address", name: "proposer" }, { type: "bytes32", name: "policyHash" }, { type: "bytes32", name: "marketStateHash" }, { type: "tuple[]", name: "actions", components: [{ type: "uint8", name: "kind" }, { type: "address", name: "adapter" }, { type: "address", name: "asset" }, { type: "uint256", name: "amount" }, { type: "bytes", name: "params" }] }, { type: "bytes32", name: "dryRunResultHash" }, { type: "uint64", name: "submittedAt" }, { type: "uint64", name: "expiresAt" }, { type: "uint64", name: "earliestExecution" }, { type: "uint8", name: "state" }, { type: "bytes32", name: "verdictHash" }] }], stateMutability: "view" },
  { type: "function", name: "listPending", inputs: [], outputs: [{ type: "bytes32[]" }], stateMutability: "view" },
  { type: "function", name: "isAuthorizedAgent", inputs: [{ type: "address", name: "agent" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "executionTimelock", inputs: [], outputs: [{ type: "uint64" }], stateMutability: "view" },
  { type: "function", name: "submitProposal", inputs: [{ type: "bytes32", name: "policyHash" }, { type: "bytes32", name: "marketStateHash" }, { type: "tuple[]", name: "actions", components: [{ type: "uint8", name: "kind" }, { type: "address", name: "adapter" }, { type: "address", name: "asset" }, { type: "uint256", name: "amount" }, { type: "bytes", name: "params" }] }, { type: "bytes32", name: "dryRunResultHash" }, { type: "bytes", name: "agentSig" }], outputs: [{ type: "bytes32", name: "proposalId" }], stateMutability: "nonpayable" },
  { type: "function", name: "approveProposal", inputs: [{ type: "bytes32", name: "proposalId" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "cancelProposal", inputs: [{ type: "bytes32", name: "proposalId" }, { type: "string", name: "reason" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "executeProposal", inputs: [{ type: "bytes32", name: "proposalId" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "markExecuted", inputs: [{ type: "bytes32", name: "proposalId" }, { type: "bytes32", name: "postStateHash" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "ProposalSubmitted", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "address", name: "proposer", indexed: true }, { type: "bytes32", name: "policyHash" }] },
  { type: "event", name: "ProposalApproved", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "address", name: "approver", indexed: true }] },
  { type: "event", name: "ProposalRejected", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "bytes", name: "reason" }] },
  { type: "event", name: "ProposalCancelled", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "string", name: "reason" }] },
  { type: "event", name: "ProposalExecuted", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "bytes32", name: "postStateHash" }] },
  { type: "event", name: "ProposalExpired", inputs: [{ type: "bytes32", name: "id", indexed: true }] },
  { type: "event", name: "AgentBondSlashed", inputs: [{ type: "address", name: "agent", indexed: true }, { type: "uint256", name: "amount" }, { type: "bytes32", name: "proposalId", indexed: true }] },
] as const;

const POLICY_REGISTRY_ABI = [
  { type: "function", name: "activePolicyHash", inputs: [], outputs: [{ type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "activePolicy", inputs: [], outputs: [{ type: "bytes32", name: "hash" }, { type: "tuple", name: "", components: [{ type: "bytes32", name: "hash" }, { type: "bytes32", name: "codeHash" }, { type: "address", name: "author" }, { type: "uint64", name: "activatedAt" }, { type: "uint64", name: "proposedAt" }, { type: "bool", name: "active" }, { type: "bytes32[]", name: "hardConstraintIds" }] }], stateMutability: "view" },
  { type: "function", name: "getPolicy", inputs: [{ type: "bytes32", name: "hash" }], outputs: [{ type: "bytes", name: "bytecode" }, { type: "tuple", name: "meta", components: [{ type: "bytes32", name: "hash" }, { type: "bytes32", name: "codeHash" }, { type: "address", name: "author" }, { type: "uint64", name: "activatedAt" }, { type: "uint64", name: "proposedAt" }, { type: "bool", name: "active" }, { type: "bytes32[]", name: "hardConstraintIds" }] }], stateMutability: "view" },
  { type: "function", name: "proposeUpdate", inputs: [{ type: "bytes", name: "newBytecode" }], outputs: [{ type: "bytes32", name: "newHash" }], stateMutability: "nonpayable" },
  { type: "function", name: "activateUpdate", inputs: [{ type: "bytes32", name: "newHash" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getHardConstraints", inputs: [{ type: "bytes32", name: "policyHash" }], outputs: [{ type: "bytes32[]" }], stateMutability: "view" },
  { type: "event", name: "PolicyProposed", inputs: [{ type: "bytes32", name: "hash", indexed: true }, { type: "address", name: "by", indexed: true }, { type: "uint64", name: "earliestActivation" }] },
  { type: "event", name: "PolicyActivated", inputs: [{ type: "bytes32", name: "hash", indexed: true }, { type: "bytes32", name: "previousHash", indexed: true }] },
  { type: "event", name: "PolicyRejected", inputs: [{ type: "bytes32", name: "hash", indexed: true }, { type: "bytes", name: "reason" }] },
] as const;

const TAX_ENGINE_ABI = [
  { type: "function", name: "recordExecution", inputs: [{ type: "bytes32", name: "proposalId" }, { type: "tuple[]", name: "actions", components: [{ type: "uint8", name: "kind" }, { type: "address", name: "adapter" }, { type: "address", name: "asset" }, { type: "uint256", name: "amount" }, { type: "bytes", name: "params" }] }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "recordCorporateAction", inputs: [{ type: "address", name: "asset" }, { type: "uint8", name: "kind" }, { type: "uint256", name: "amount" }, { type: "bytes32", name: "metadata" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "exportPeriod", inputs: [{ type: "uint64", name: "startTs" }, { type: "uint64", name: "endTs" }], outputs: [{ type: "tuple[]", name: "", components: [{ type: "bytes32", name: "id" }, { type: "bytes32", name: "proposalId" }, { type: "uint64", name: "occurredAt" }, { type: "uint8", name: "kind" }, { type: "address", name: "asset" }, { type: "uint256", name: "amount" }, { type: "uint256", name: "costBasis" }, { type: "bytes8", name: "jurisdiction" }, { type: "bytes32", name: "metadata" }] }], stateMutability: "view" },
  { type: "function", name: "jurisdiction", inputs: [], outputs: [{ type: "bytes8" }], stateMutability: "view" },
  { type: "function", name: "lotMethod", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "setJurisdiction", inputs: [{ type: "bytes8", name: "code" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setLotMethod", inputs: [{ type: "uint8", name: "method" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "TaxEventRecorded", inputs: [{ type: "bytes32", name: "id", indexed: true }, { type: "bytes32", name: "proposalId", indexed: true }, { type: "uint8", name: "kind" }, { type: "address", name: "asset", indexed: true }, { type: "uint256", name: "amount" }, { type: "int256", name: "realizedPnL" }] },
  { type: "event", name: "JurisdictionChanged", inputs: [{ type: "bytes8", name: "from" }, { type: "bytes8", name: "to" }] },
  { type: "event", name: "LotMethodChanged", inputs: [{ type: "uint8", name: "from" }, { type: "uint8", name: "to" }] },
] as const;

// ─── Types ───

export interface HelixClientConfig {
  vaultAddress: Address;
  proposalRegistryAddress: Address;
  policyRegistryAddress: Address;
  taxEngineAddress: Address;
  rpcUrl: string;
  chain?: Chain;
  /** Optional wallet for signing transactions (required for submitProposal) */
  walletClient?: WalletClient;
}

export interface TreasurySnapshot {
  navUsdc: bigint;
  assets: Array<{ token: Address; balance: bigint; priceUsdc: bigint }>;
  paused: boolean;
  timestamp: number;
}

export interface ProposalSummary {
  id: bigint;
  state: "submitted" | "accepted" | "approved" | "executed" | "rejected" | "cancelled";
  agent: Address;
  actionCount: number;
  submittedAt: number;
  executableAt: number;
}

export interface TaxReport {
  jurisdiction: "US_FIFO" | "US_LIFO" | "US_HIFO" | "UK_HMRC" | "EU_GENERIC";
  taxYear: number;
  events: TaxEvent[];
  summary: { totalGainLoss: bigint; currency: string };
}

export interface TaxEvent {
  kind: string;
  token: Address;
  amount: bigint;
  costBasisUsdc: bigint;
  proceedsUsdc: bigint;
  gainLossUsdc: bigint;
  timestamp: number;
  txHash: `0x${string}`;
}

// ─── Client ───

export class HelixClient {
  private readonly public: PublicClient;
  private readonly cfg: HelixClientConfig;

  constructor(cfg: HelixClientConfig) {
    this.cfg = cfg;
    this.public = createPublicClient({
      chain: cfg.chain ?? arbitrumSepolia,
      transport: http(cfg.rpcUrl),
    });
  }

  // ──────────── Treasury views ────────────

  /** Returns current NAV in USDC (6 decimals) */
  async getNAV(): Promise<bigint> {
    return this.public.readContract({
      address: this.cfg.vaultAddress,
      abi: TREASURY_VAULT_ABI,
      functionName: "getNAV",
    });
  }

  /** Returns full treasury snapshot: balances + prices + paused state */
  async getSnapshot(): Promise<TreasurySnapshot> {
    const [paused, nav] = await Promise.all([
      this.public.readContract({ address: this.cfg.vaultAddress, abi: TREASURY_VAULT_ABI, functionName: "paused" }),
      this.getNAV(),
    ]);
    return {
      navUsdc: nav,
      assets: [], // TODO(mulerun): decode getState() response
      paused,
      timestamp: Math.floor(Date.now() / 1000),
    };
  }

  // ──────────── Proposal views ────────────

  /** Returns all proposals from id 0 to nextProposalId-1 */
  async listProposals(filter?: { state?: ProposalSummary["state"] }): Promise<ProposalSummary[]> {
    const pendingIds = await this.public.readContract({
      address: this.cfg.proposalRegistryAddress,
      abi: PROPOSAL_REGISTRY_ABI,
      functionName: "listPending",
    });
    const summaries: ProposalSummary[] = [];
    for (const id of pendingIds) {
      const raw = await this.public.readContract({
        address: this.cfg.proposalRegistryAddress,
        abi: PROPOSAL_REGISTRY_ABI,
        functionName: "getProposal",
        args: [id],
      });
      const stateMap: Record<number, ProposalSummary["state"]> = {
        0: "submitted", 1: "approved", 2: "rejected", 3: "executed", 4: "cancelled",
      };
      const proposal = raw as any;
      const summary: ProposalSummary = {
        id: BigInt(proposal.id),
        state: stateMap[Number(proposal.state)] ?? "submitted",
        agent: proposal.proposer,
        actionCount: proposal.actions?.length ?? 0,
        submittedAt: Number(proposal.submittedAt),
        executableAt: Number(proposal.earliestExecution),
      };
      if (!filter?.state || summary.state === filter.state) {
        summaries.push(summary);
      }
    }
    return summaries;
  }

  async getProposal(id: `0x${string}`): Promise<ProposalSummary> {
    const raw = await this.public.readContract({
      address: this.cfg.proposalRegistryAddress,
      abi: PROPOSAL_REGISTRY_ABI,
      functionName: "getProposal",
      args: [id],
    }) as any;
    const stateMap: Record<number, ProposalSummary["state"]> = {
      0: "submitted", 1: "approved", 2: "rejected", 3: "executed", 4: "cancelled",
    };
    return {
      id: BigInt(raw.id),
      state: stateMap[Number(raw.state)] ?? "submitted",
      agent: raw.proposer,
      actionCount: raw.actions?.length ?? 0,
      submittedAt: Number(raw.submittedAt),
      executableAt: Number(raw.earliestExecution),
    };
  }

  async isExecutable(id: `0x${string}`): Promise<boolean> {
    const proposal = await this.getProposal(id);
    if (proposal.state !== "approved") return false;
    const now = Math.floor(Date.now() / 1000);
    return now >= proposal.executableAt;
  }

  // ──────────── Policy views ────────────

  async getActivePolicyHash(): Promise<`0x${string}`> {
    return this.public.readContract({
      address: this.cfg.policyRegistryAddress,
      abi: POLICY_REGISTRY_ABI,
      functionName: "activePolicyHash",
    });
  }

  async getActivePolicyBytecode(): Promise<`0x${string}`> {
    return this.public.readContract({
      address: this.cfg.policyRegistryAddress,
      abi: POLICY_REGISTRY_ABI,
      functionName: "activePolicyBytecode",
    });
  }

  // ──────────── Tax engine ────────────

  /** Export a jurisdiction-specific tax report for a given year */
  async exportTaxReport(jurisdiction: TaxReport["jurisdiction"], taxYear: number): Promise<TaxReport> {
    // Compute start/end timestamps for the tax year
    const startTs = BigInt(Math.floor(new Date(`${taxYear}-01-01T00:00:00Z`).getTime() / 1000));
    const endTs = BigInt(Math.floor(new Date(`${taxYear + 1}-01-01T00:00:00Z`).getTime() / 1000));

    const rawEvents = await this.public.readContract({
      address: this.cfg.taxEngineAddress,
      abi: TAX_ENGINE_ABI,
      functionName: "exportPeriod",
      args: [startTs, endTs],
    }) as any[];

    const kindMap = ["REALIZED_GAIN", "REALIZED_LOSS", "DIVIDEND", "STAKING_REWARD", "CORPORATE_ACTION", "INTERNAL_TRANSFER"];
    const events: TaxEvent[] = (rawEvents ?? []).map((e: any) => ({
      kind: kindMap[Number(e.kind)] ?? "UNKNOWN",
      token: e.asset,
      amount: BigInt(e.amount),
      costBasisUsdc: BigInt(e.costBasis),
      proceedsUsdc: 0n,
      gainLossUsdc: 0n,
      timestamp: Number(e.occurredAt),
      txHash: "0x" as `0x${string}`,
    }));

    const totalGainLoss = events.reduce((sum, e) => sum + e.gainLossUsdc, 0n);

    return {
      jurisdiction,
      taxYear,
      events,
      summary: { totalGainLoss, currency: "USD" },
    };
  }

  // ──────────── Event subscriptions ────────────

  /** Subscribe to Vault events (Deposited, Executed, EmergencyPaused, ...) */
  watchVaultEvents(callback: (event: unknown) => void): () => void {
    const unwatch = this.public.watchContractEvent({
      address: this.cfg.vaultAddress,
      abi: TREASURY_VAULT_ABI,
      onLogs: (logs) => logs.forEach(callback),
    });
    return unwatch;
  }
}

// Re-export everything from sub-modules as SDK surface grows
export * from "./policy.js";
export * from "./types.js";
